// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "driveencoders.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

driveencoders::driveencoders(double left, double right, double leftspeed, double rightspeed): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
		m_left = left;
		m_right = right;
		m_lspeed = leftspeed;
		m_rspeed = rightspeed;
		m_done = false;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void driveencoders::Initialize() {
	SetTimeout(7);
	m_done = false;
}

// Called repeatedly when this Command is scheduled to run
void driveencoders::Execute() {
	Robot::drivetrain->Encoder(m_left, m_right, m_lspeed, m_rspeed);
		m_done = Robot::drivetrain->isMove();
}

// Make this return true when this Command no longer needs to run execute()
bool driveencoders::IsFinished() {
    return m_done || IsTimedOut();
}

// Called once after isFinished returns true
void driveencoders::End() {
	Robot::drivetrain->EncoderDone();

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void driveencoders::Interrupted() {

}
