// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ClimbCommand.h"
#include "Commands/GearCommand.h"
#include "Commands/SlowTankDriveCommand.h"
#include "Commands/TankDriveCommand.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    rightJoystick.reset(new Joystick(1));
    
    leftJoystick.reset(new Joystick(0));
    
    climbButton.reset(new JoystickButton(leftJoystick.get(), 1));
    climbButton->WhileHeld(new ClimbCommand());
    gearButton.reset(new JoystickButton(leftJoystick.get(), 1));
    gearButton->WhileHeld(new GearCommand());
    slowTankDriveButton.reset(new JoystickButton(leftJoystick.get(), 1));
    slowTankDriveButton->WhileHeld(new SlowTankDriveCommand());

    // SmartDashboard Buttons
    SmartDashboard::PutData("Climb Command", new ClimbCommand());
    SmartDashboard::PutData("Gear Command", new GearCommand());
    SmartDashboard::PutData("Slow Tank Drive Command", new SlowTankDriveCommand());
    SmartDashboard::PutData("Tank Drive Command", new TankDriveCommand());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getLeftJoystick() {
   return leftJoystick;
}

std::shared_ptr<Joystick> OI::getRightJoystick() {
   return rightJoystick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
