// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/climbfast.h"
#include "Commands/climbslow.h"
#include "Commands/climbstop.h"
#include "Commands/driveauto.h"
#include "Commands/drivewithjoysticks.h"
#include "Commands/geardown.h"
#include "Commands/gearpunch.h"
#include "Commands/gearretract.h"
#include "Commands/gearup.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    xbox.reset(new Joystick(0));
    logitech.reset(new Joystick(5));
    
    rightthumb.reset(new JoystickButton(logitech.get(), 9));
    rightthumb->WhenPressed(new gearpunch());
    leftthumb.reset(new JoystickButton(logitech.get(), 10));
    leftthumb->WhenPressed(new gearretract());
    l1.reset(new JoystickButton(logitech.get(), 5));
    l1->WhenPressed(new climbstop());
    y.reset(new JoystickButton(logitech.get(), 4));
    y->WhenPressed(new climbfast());
    x.reset(new JoystickButton(logitech.get(), 3));
    x->WhenPressed(new climbslow());
    b.reset(new JoystickButton(logitech.get(), 2));
    b->WhenPressed(new geardown());
    a.reset(new JoystickButton(logitech.get(), 1));
    a->WhenPressed(new gearup());



    // SmartDashboard Buttons
    SmartDashboard::PutData("climbstop", new climbstop());
    SmartDashboard::PutData("climbfast", new climbfast());
    SmartDashboard::PutData("climbslow", new climbslow());
    SmartDashboard::PutData("gearretract", new gearretract());
    SmartDashboard::PutData("gearpunch", new gearpunch());
    SmartDashboard::PutData("geardown", new geardown());
    SmartDashboard::PutData("gearup", new gearup());
    SmartDashboard::PutData("drivewithjoysticks", new drivewithjoysticks());
    SmartDashboard::PutData("driveauto", new driveauto());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getxbox() {
   return xbox;
}


std::shared_ptr<Joystick> OI::getlogitech() {
   return logitech;
}



// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
