// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ctrlib/CANTalon.h"


#include "Drivetrain.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/drivewithjoysticks.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Drivetrain::Drivetrain() : Subsystem("Drivetrain") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    frontleft = RobotMap::drivetrainfrontleft;
    frontright = RobotMap::drivetrainfrontright;
    robotDrive21 = RobotMap::drivetrainRobotDrive21;
    rearleft = RobotMap::drivetrainrearleft;
    rearright = RobotMap::drivetrainrearright;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


}

void Drivetrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new drivewithjoysticks());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Drivetrain::TankDrive(std::shared_ptr<Joystick>xbox){
	if(xbox->GetRawButton(6)==1){
		robotDrive21->TankDrive(0.6*xbox->GetRawAxis(5), 0.6*xbox->GetRawAxis(1));
	}
	else if(xbox->GetRawAxis(2)==1){
		robotDrive21->TankDrive(-.5*xbox->GetRawAxis(1), -.5*xbox->GetRawAxis(5));
	}
	else{
		robotDrive21->TankDrive(-1*xbox->GetRawAxis(1), -1*xbox->GetRawAxis(5));
	}
}

void Drivetrain::TankDrive(double left, double right){
	robotDrive21->TankDrive(left, right);
}

void Drivetrain::driveauto(){
	//robotDrive21->TankDrive(-0.36,-0.32);
	robotDrive21->SetSafetyEnabled(false);
	frontleft->SetControlMode(CANTalon::kPosition);
	frontright->SetControlMode(CANTalon::kPosition);
	frontright->SetClosedLoopOutputDirection(true);
	frontleft->EnableControl();
	frontright->EnableControl();
	frontleft->Set(50.0);
	frontright->Set(50.0);
}

void Drivetrain::drivestop(){
	robotDrive21->TankDrive(0.0,0.0);
}

