// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/autonomousdrive.h"
#include "Commands/drivebackward.h"
#include "Commands/driveslow.h"
#include "Commands/drivestraight.h"
#include "Commands/drivewithjoystick.h"
#include "Commands/motionprofile.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    xbox.reset(new Joystick(0));
    
    rightbumper.reset(new JoystickButton(xbox.get(), 6));
    rightbumper->WhileHeld(new drivebackward());
    leftbumper.reset(new JoystickButton(xbox.get(), 5));
    leftbumper->WhileHeld(new driveslow());
    b.reset(new JoystickButton(xbox.get(), 2));
    b->WhenPressed(new motionprofile());
    a.reset(new JoystickButton(xbox.get(), 1));
    a->WhileHeld(new drivestraight());

    // SmartDashboard Buttons
    SmartDashboard::PutData("motionprofile", new motionprofile());
    SmartDashboard::PutData("drivewithjoystick", new drivewithjoystick());
    SmartDashboard::PutData("drivebackward", new drivebackward());
    SmartDashboard::PutData("driveslow", new driveslow());
    SmartDashboard::PutData("drivestraight", new drivestraight());
    SmartDashboard::PutData("autonomousdrive", new autonomousdrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getxbox() {
   return xbox;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
