// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Robot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
std::shared_ptr<Drivetrain> Robot::drivetrain;
std::unique_ptr<OI> Robot::oi;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION

void Robot::RobotInit() {
	RobotMap::init();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    drivetrain.reset(new Drivetrain());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	// This MUST be here. If the OI creates Commands (which it very likely
	// will), constructing it during the construction of CommandBase (from
	// which commands extend), subsystems are not guaranteed to be
	// yet. Thus, their requires() statements may grab null pointers. Bad
	// news. Don't move it.
	oi.reset(new OI());

	// instantiate the command used for the autonomous period
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	autonomousCommand.reset(new autonomousdrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
  }

/**
 * This function is called when the disabled button is hit.
 * You can use it to reset subsystems before shutting down.
 */
void Robot::DisabledInit(){

}

void Robot::DisabledPeriodic() {
	Scheduler::GetInstance()->Run();
}

void Robot::AutonomousInit() {
	if (autonomousCommand.get() != nullptr)
		autonomousCommand->Start();

	//Enable talons
	//RobotMap::drivetrainfl->EnableControl();
	//RobotMap::drivetrainfr->EnableControl();

	//Set Talons to avoid timouts
	//RobotMap::drivetrainfl->Set(0.0);
	//RobotMap::drivetrainfr->Set(0.0);


	//Zero the encoders when Autonomous initializes
	//RobotMap::drivetrainfl->SetPosition(0.0);
	//RobotMap::drivetrainfr->SetPosition(0.0);
}

void Robot::AutonomousPeriodic() {
	Scheduler::GetInstance()->Run();

	//Put data to the smartdashboard
	SmartDashboard::PutNumber("Left Encoder Position",RobotMap::drivetrainfl->GetPosition());
	SmartDashboard::PutNumber("Right Encoder Position",RobotMap::drivetrainfr->GetPosition());
	SmartDashboard::PutNumber("Left Encoder Speed", RobotMap::drivetrainfl->GetSpeed());
	SmartDashboard::PutNumber("Right Encoder Speed", RobotMap::drivetrainfr->GetSpeed());
}

void Robot::TeleopInit() {
	// This makes sure that the autonomous stops running when
	// teleop starts running. If you want the autonomous to
	// continue until interrupted by another command, remove
	// these lines or comment it out.
	if (autonomousCommand.get() != nullptr)
		autonomousCommand->Cancel();

	//Zero Encoders
	//RobotMap::drivetrainfl->SetPosition(0.0);
	//RobotMap::drivetrainfr->SetPosition(0.0);

	//Enable talons
	//RobotMap::drivetrainfl->EnableControl();
	//RobotMap::drivetrainfr->EnableControl();

	//Set a value to initialize the talons
	//RobotMap::drivetrainfl->Set(0.0);
	//RobotMap::drivetrainfr->Set(0.0);
}

void Robot::TeleopPeriodic() {
	Scheduler::GetInstance()->Run();

	//Put data to the smartdashboard
	SmartDashboard::PutNumber("Left Encoder Position",RobotMap::drivetrainfl->GetPosition());
	SmartDashboard::PutNumber("Right Encoder Position",RobotMap::drivetrainfr->GetPosition());
	SmartDashboard::PutNumber("Left Encoder Speed", RobotMap::drivetrainfl->GetSpeed());
	SmartDashboard::PutNumber("Right Encoder Speed", RobotMap::drivetrainfr->GetSpeed());
}

void Robot::TestPeriodic() {
	lw->Run();
}

START_ROBOT_CLASS(Robot);

